### ISSUE TITLE
mcdisplay-webgl call should not use --default

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#131]
When running the instrument 
https://elearn1.fysik.dtu.dk/instrument-menu/swedness/Ni_TAS_reduced 
with parameters EI=5 EF=5 QHK=0 QL=1

the call to mcdisplay-webgl hangs the whole worker 
<pre>
(mcvenv)www-data@elearn1:/srv/mcweb/McWeb/mcsimrunner$ !.
./manage.py runworker
MainThread            : looking for simruns...
MainThread            : delegating simrun for Ni_TAS_reduced...
MainThread            : idle...
T1 (Ni_TAS_reduced)   : simrun (mcrun.pl --mpi=10 Ni_TAS_reduced.instr -d mcstas -n 1000000 EI=5 EF=5 QHK=0 QL=1 Temperature_K=70)...
T1 (Ni_TAS_reduced)   : data: static/data/pkwi_Ni_TAS_reduced_20170904_191257
T1 (Ni_TAS_reduced)   : mcdisplay: mcdisplay-webgl --default --nobrowse --ncount=300 --dirname=mcdisplay Ni_TAS_reduced.instr
</pre>

- The issue is that --default does not fill in the parameters given from the user interface. --default uses the instr default (that indeed do not make the instr produce data), but whatsoever mcdisplay-webgl should fill the values given and let mcrun / the instr binary handle the rest.

The "hidden" problem is that the command mcdisplay: mcdisplay-webgl --default --nobrowse --ncount=300 --dirname=mcdisplay Ni_TAS_reduced.instr results in
<pre>
INFO: Using directory: "mcdisplay"
INFO: Using existing binary: ./Ni_TAS_reduced.out
INFO: ===
templateTAS: ERROR: neutron beam energy is not defined (EI, EF, KI, KF)
Traceback (most recent call last):
  File "/usr/share/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/../../mccodelib/../../../bin/../tools/Python/mcrun/mcrun.py", line 372, in <module>
    main()
  File "/usr/share/mcstas/2.4.1/bin/../tools/Python/mcdisplay/webgl/../../mccodelib/../../../bin/../tools/Python/mcrun/mcrun.py", line 356, in main
    mcstas.run()
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 208, in run
    return self.runMPI(args, pipe, override_mpi)
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 227, in runMPI
    return Process(binpath).run(args, pipe=pipe)
  File "/usr/share/mcstas/2.4.1/tools/Python/mcrun/mccode.py", line 80, in run
    raise ProcessException(self.executable, args, retval)
mccode.ProcessException: Got exit status 72 from "./Ni_TAS_reduced.out --ncount 300.0 --dir mcdisplay --format McStas --trace --no-output-files"
</pre>

**Comment by willend** [comment]
It seems that the issue is related to the use of -d mcdisplay, which makes a call like
<pre>
mcdisplay-webgl Ni_TAS_reduced.out EI=5 EF=5 QHK=0 QL=1 -dmcdisplay
Instrument parameters for templateTAS (Ni_TAS_reduced.instr)
Set value of instrument parameter EI (double) [default='0']:
</pre>
... prompt for parameters even if EI etc are given, whereas 
<pre>
mcdisplay-webgl Ni_TAS_reduced.out EI=5 EF=5 QHK=0 QL=1
* Incoming beam: EI=5 [meV] KI=0 [Angs-1] Vi=0 [m/s]
* Outgoing beam: EF=5 [meV] KF=0 [Angs-1] Vf=0 [m/s]
* Incoming beam: EI=5 [meV] KI=0 [Angs-1] Vi=0 [m/s]
* Outgoing beam: EF=5 [meV] KF=0 [Angs-1] Vf=0 [m/s]
templateTAS: Detailed TAS configuration
...
</pre>
seems to work just fine
