### ISSUE TITLE
Look at issues with non-compiles / non-addable instruments at mcstas-01

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McWeb#85]
e.g. this one where the instrument now compiles, but can not be added to the DB:

<pre>
./manage.py collect_instr
instrument RITA-II created
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/mcweb/mcvenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/srv/mcweb/mcvenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/mcweb/mcvenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/mcweb/mcvenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/srv/mcweb/McWeb/mcsimrunner_ng/simrunner/management/commands/collect_instr.py", line 160, in handle
    instr.params = get_instr_params(g, i)
  File "/home/srv/mcweb/McWeb/mcsimrunner_ng/simrunner/management/commands/collect_instr.py", line 95, in get_instr_params
    l2 = l2.split(':')[1]
IndexError: list index out of range
</pre>

**Comment by climbcat** [comment]
Hi Peter, what's the status of this issue?
